version: '2'
services:
    demojhai-app:
        image: demojhai
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://demojhai-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=DemoJHAI
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=demojhai-elasticsearch:9300
        ports:
            - 8080:8080
    demojhai-mongodb:
        extends:
            file: mongodb.yml
            service: demojhai-mongodb
    demojhai-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: demojhai-elasticsearch
